# Generated by Django 4.2.3 on 2023-07-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=32)),
                ('timestamp', models.DateTimeField()),
                ('record_type', models.IntegerField()),
                ('prev_bloodsugar', models.IntegerField()),
                ('cur_bloodsugar', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'BloodSugarData',
            },
        ),
    ]
