# Generated by Django 4.2.3 on 2023-07-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='code',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
