# Generated by Django 4.2.3 on 2023-07-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_data_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='code',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
