# Generated by Django 4.2.3 on 2023-07-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_data_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='code',
            field=models.CharField(max_length=100),
        ),
    ]
