# Generated by Django 4.2.3 on 2023-07-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_data_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='cur_bloodsugar',
        ),
        migrations.RemoveField(
            model_name='data',
            name='prev_bloodsugar',
        ),
        migrations.AddField(
            model_name='data',
            name='bloodsugar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='scan_bloodsugar',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
