# Generated by Django 4.2.3 on 2023-07-06 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_data_code'),
        ('codeNumber', '0002_codenumber_device_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codenumber',
            name='device_num',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='data.data'),
        ),
    ]
