# Generated by Django 4.2.3 on 2023-07-06 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_data_code'),
        ('codeNumber', '0005_alter_codenumber_device_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codenumber',
            name='device_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.data'),
        ),
    ]
