# Generated by Django 4.2.3 on 2023-07-26 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestion', '0002_alter_suggestion_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
