# Generated by Django 4.0.3 on 2023-07-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_pet_gender_pet_profile_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='feed',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='pet',
            name='sore_spot',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
