# Generated by Django 4.0.3 on 2023-07-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_alter_pet_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='profile_url',
            field=models.URLField(),
        ),
    ]
