# Generated by Django 4.0.3 on 2023-07-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_pet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='user',
        ),
    ]
