# Generated by Django 4.2.3 on 2023-07-12 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0010_alter_pet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='fitapet/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='profile_url',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
    ]
