# Generated by Django 4.2.3 on 2023-07-18 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_alter_pet_user'),
        ('pet', '0011_pet_profile_image_alter_pet_profile_url'),
    ]

    operations = [
    ]
