# Generated by Django 4.2.3 on 2023-07-18 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pet', '0012_merge_20230718_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='feed',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('unspayed female', 'Unspayed Female'), ('spayed female', 'Spayed Female'), ('unneutered male', 'Unneutered Male'), ('neutered male', 'Neutered Male')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sore_spot',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
