# Generated by Django 4.0.3 on 2023-07-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0013_alter_pet_feed_alter_pet_gender_alter_pet_sore_spot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='started_date',
            field=models.DateField(),
        ),
    ]
