# Generated by Django 4.0.3 on 2023-07-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0014_alter_pet_started_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='started_date',
            field=models.DateTimeField(),
        ),
    ]
