# Generated by Django 4.0.3 on 2023-07-25 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pet', '0015_alter_pet_started_date'),
    ]

    operations = []
