# Generated by Django 4.0.3 on 2023-07-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0017_pet_user'),
    ]

    operations = [
        # migrations.AddField(
        #    model_name='pet',
        #    name='profile_image',
        #    field=models.ImageField(blank=True, null=True, upload_to='fitapet/'),
        # ),
    ]
