# Generated by Django 4.2.3 on 2023-07-26 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0021_pet_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('수컷', '수컷'), ('암컷', '암컷'), ('중성화된 수컷', '중성화된 수컷'), ('중성화된 암컷', '중성화된 암컷')], max_length=20),
        ),
    ]
